[build]
  # Netlify doesn't need to build anything - we're serving static files
  publish = "frontend"
  command = "echo 'No build needed - static site'"

[[redirects]]
  # SPA fallback - all routes go to index.html
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  # No build environment needed for static site
